DROP DATABASE IF EXISTS QUARKUS;
CREATE DATABASE IF NOT EXISTS QUARKUS;

USE QUARKUS;

CREATE TABLE T_PERSON
(
MOTE VARCHAR(50) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
EDAD int not null DEFAult 18,
primary key (MOTE)
) ENGINE INNODB;